### ISSUE TITLE
can not join discord

### ISSUE THREAD

**Issue by hiyyg** [yangjiheng/3DGS_and_Beyond_Docs#1]
![image](https://github.com/yangjiheng/3DGS_and_Beyond_Docs/assets/62354758/e5e0d6fb-b72e-4b6c-9414-d1ccc8de581a)

**Comment by yangjiheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/62354758/337964298-e5e0d6fb-b72e-4b6c-9414-d1ccc8de581a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzUzNDUsIm5iZiI6MTcxODAzNTA0NSwicGF0aCI6Ii82MjM1NDc1OC8zMzc5NjQyOTgtZTVlMGQ2ZmItYjcyZS00YjZjLTk0MTQtZDFjY2M4ZGU1ODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE1NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NTBkODA2ZDQwOTViODdjOWJmZTZkYjU3NzQzMDMwNDk5ZWViYjZkODE2ZThmZjFkOTFjMTY2OGFlYTRkZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3v8XvPV6s8J_aYcY3vE3Kdj_NaF4_rwg0NPVU_RPW7E)

Sorry we close discord server for now since there is very little energy to maintain all these channels. We probably will resume this afterwards. For now, please add my wechat account: jiheng_yang, and I can invite you into wechat groups.
