### ISSUE TITLE
"3DGS Model Compactness Optimization" column includes mismatching works

### ISSUE THREAD

**Issue by YeJiangnan1029** [yangjiheng/3DGS_and_Beyond_Docs#2]
It seems that the newest works 
"Tetrahedron Splatting for 3D Generation"
"Adversarial Generation of Hierarchical Gaussians for 3D Generative Model"
belongs to "Geometry Reconstruction" or "AIGC" column, rather than "Model Compactness Optimization" :D

**Comment by yangjiheng** [comment]
> It seems that the newest works "Tetrahedron Splatting for 3D Generation" "Adversarial Generation of Hierarchical Gaussians for 3D Generative Model" belongs to "Geometry Reconstruction" or "AIGC" column, rather than "Model Compactness Optimization" :D

Yeah! Thanks  for the correction, it makes more sense for:
Tetrahedron Splatting for 3D Generation to be in "Geometry Reconstruction" 
and 
Adversarial Generation of Hierarchical Gaussians for 3D Generative Model to be in "AIGC"

 I just updated accordingly, thanks again for point it out, it should be an error on massive update a couple days back. Please let me know if you spot any other issues!
